[tool.black]
line-length = 99
target-version = ["py311"]
exclude = "(.venv)"

[tool.isort]
profile = "black"
skip_gitignore = true
use_parentheses = true
combine_as_imports = true
force_grid_wrap = 2
lines_between_types = 1
lines_after_imports = -1
include_trailing_comma = true
skip_glob = [".venv/*"]

[tool.autoflake]
in-place = true
recursive = true
remove-all-unused-imports = true
remove-unused-variables = true
quiet = true
exclude = [".venv"]
